### ISSUE TITLE
When unreachable yumrepos are present, os_patching does not restart properly

### ISSUE THREAD

**Issue by rnelson0** [albatrossflavour/puppet_os_patching#36]
I have a leftover repo from an upgrade of PE called `pe_repo` (the latest is `pc_repo`) and it is not reachable. `needs_restarting` errors out, which results in the `reboots => reboot_required` key having the value `false`. (fact output truncated for clarity)
```
[root@server ~]# /usr/bin/needs-restarting
Traceback (most recent call last):
  File "/usr/bin/needs-restarting", line 173, in <module>
    sys.exit(main(sys.argv))
  File "/usr/bin/needs-restarting", line 154, in main
    for oldpkg in my.pkgSack.searchFiles(just_fn): # ghostfiles are always bogons
  File "/usr/lib/python2.6/site-packages/yum/packageSack.py", line 472, in searchFiles
    return self._computeAggregateListResult("searchFiles", name)
  File "/usr/lib/python2.6/site-packages/yum/packageSack.py", line 599, in _computeAggregateListResult
    sackResult = apply(method, args)
  File "/usr/lib/python2.6/site-packages/yum/sqlitesack.py", line 46, in newFunc
    return func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/yum/sqlitesack.py", line 957, in searchFiles
    self.populate(repo, mdtype='filelists')
  File "/usr/lib/python2.6/site-packages/yum/yumRepo.py", line 173, in populate
    db_fn = repo._retrieveMD(mydbtype)
  File "/usr/lib/python2.6/site-packages/yum/yumRepo.py", line 1654, in _retrieveMD
    size=thisdata.size)
  File "/usr/lib/python2.6/site-packages/yum/yumRepo.py", line 842, in _getFile
    raise Errors.NoMoreMirrorsRepoError, errstr
yum.Errors.NoMoreMirrorsRepoError: failure: repodata/0708e3d04e17e2d229a069a9646e80019a1433a5-filelists.sqlite.bz2 from pe_repo: [Errno 256] No more mirrors to try.

[root@server ~]# facter -p os_patching
{
  last_run => {
    date => "2018-09-05T19:21:16+00:00",
    message => "Patching complete",
    return_code => "Success",
    post_reboot => "true",
    security_only => "false",
    job_id => "10"
  },
  reboots => {
    reboot_required => false,
    apps_needing_restart => {},
    app_restart_required => false
  }
}
```

When removing the repo, `reboot_required` has the correct status:
```
[root@server ~]# rm /etc/yum.repos.d/pe_repo.repo
rm: remove regular file `/etc/yum.repos.d/pe_repo.repo'? y
[root@server ~]# /usr/local/bin/os_patching_fact_generation.sh
[root@server ~]# facter -p os_patching
{
  patch_window => "trustwave",
  reboots => {
    reboot_required => true,
    apps_needing_restart => {
      3580 => "/sbin/mingetty/dev/tty2",
      626 => "/sbin/udevd-d",
      2921 => "qmgr-l-tfifo-u",
      19859 => "pickup-l-tfifo-u",
      20073 => "-bash",
      20115 => "-bash",
      20114 => "su-",
      20110 => "sudosu-",
      1982 => "hald-runner",
      1969 => "/usr/sbin/acpid",
      3472 => "/opt/puppetlabs/puppet/bin/pxp-agent",
      1981 => "hald",
      ...
    },
    app_restart_required => true
  }
}
```

Note that `last_run` indicates a reboot happened, but it in fact did not as `needs-restarting` aborted during its run, shown by uptime and an email to root:
```
[root@server ~]# uptime
 19:54:42 up 113 days, 18:36,  1 user,  load average: 2.21, 2.38, 3.36


&
Message 163:
From "ABRT Daemon <DoNotReply>"@server.localdomain  Wed Sep  5 19:33:28 2018
Return-Path: <"ABRT Daemon <DoNotReply>"@server.localdomain>
X-Original-To: root@localhost
Delivered-To: root@localhost.localdomain
Date: Wed, 05 Sep 2018 19:33:28 +0000
From: "ABRT Daemon <DoNotReply>"@server.localdomain
To: "root@localhost"@server.localdomain
Subject: "[abrt] a crash has been detected"
User-Agent: Heirloom mailx 12.4 7/29/08
Content-Type: text/plain; charset=us-ascii
Status: R

abrt_version:   2.0.8
cmdline:        /usr/bin/python -tt /usr/bin/needs-restarting
event_log:
executable:     /usr/bin/needs-restarting
hostname:       server
kernel:         2.6.32-696.13.2.el6.x86_64
last_occurrence: 1536176008
machineid:      sosreport_uploader-dmidecode=a276d7999564169970274e564583650ab7aa49ff4d399a445139ea17d2198515
pkg_arch:       noarch
pkg_epoch:      0
pkg_fingerprint: 199E 2F91 FD43 1D51
pkg_name:       yum-utils
pkg_release:    42.el6_10
pkg_vendor:     Red Hat, Inc.
pkg_version:    1.1.30
time:           Wed 05 Sep 2018 07:32:19 PM UTC
uid:            0
username:       root

sosreport.tar.xz: Binary file, 1461172 bytes

backtrace:
:yumRepo.py:842:_getFile:NoMoreMirrorsRepoError: failure: repodata/0708e3d04e17e2d229a069a9646e80019a1433a5-filelists.sqlite.bz2 from pe_repo: [Errno 256] No more mirrors to try.
:
:Traceback (most recent call last):
:  File "/usr/bin/needs-restarting", line 173, in <module>
:    sys.exit(main(sys.argv))
:  File "/usr/bin/needs-restarting", line 154, in main
:    for oldpkg in my.pkgSack.searchFiles(just_fn): # ghostfiles are always bogons
:  File "/usr/lib/python2.6/site-packages/yum/packageSack.py", line 472, in searchFiles
:    return self._computeAggregateListResult("searchFiles", name)
:  File "/usr/lib/python2.6/site-packages/yum/packageSack.py", line 599, in _computeAggregateListResult
:    sackResult = apply(method, args)
:  File "/usr/lib/python2.6/site-packages/yum/sqlitesack.py", line 46, in newFunc
:    return func(*args, **kwargs)
:  File "/usr/lib/python2.6/site-packages/yum/sqlitesack.py", line 957, in searchFiles
:    self.populate(repo, mdtype='filelists')
:  File "/usr/lib/python2.6/site-packages/yum/yumRepo.py", line 173, in populate
:    db_fn = repo._retrieveMD(mydbtype)
:  File "/usr/lib/python2.6/site-packages/yum/yumRepo.py", line 1654, in _retrieveMD
:    size=thisdata.size)
:  File "/usr/lib/python2.6/site-packages/yum/yumRepo.py", line 842, in _getFile
:    raise Errors.NoMoreMirrorsRepoError, errstr
:NoMoreMirrorsRepoError: failure: repodata/0708e3d04e17e2d229a069a9646e80019a1433a5-filelists.sqlite.bz2 from pe_repo: [Errno 256] No more mirrors to try.
:
:Local variables in innermost frame:
:e: URLGrabError(256, 'No more mirrors to try.')
:start: None
:url: None
:text: 'pe_repo/filelists_db'
:self: <yum.yumRepo.YumRepository object at 0x7fc80d6b1590>
:cache: True
:reget: 'simple'
:relative: 'repodata/0708e3d04e17e2d229a069a9646e80019a1433a5-filelists.sqlite.bz2'
:headers: ()
:checkfunc: <function checkfunc at 0x2c6eb18>
:errstr: 'failure: repodata/0708e3d04e17e2d229a069a9646e80019a1433a5-filelists.sqlite.bz2 from pe_repo: [Errno 256] No more mirrors to try.'
:copy_local: 1
:end: None
:local: '/var/cache/yum/x86_64/6Server/pe_repo/0708e3d04e17e2d229a069a9646e80019a1433a5-filelists.sqlite.bz2'
:size: '189770'

environ:
:TERM=linux
:PATH=/usr/bin:/usr/sbin:/bin:/usr/local/bin
:PWD=/
:LANG=en_US.UTF-8
:SHLVL=3
:_=/usr/bin/needs-restarting
```

**Comment by rnelson0** [comment]
The `last_run` issue is because [`output`](https://github.com/albatrossflavour/puppet_os_patching/blob/389e257b41fa640a85f2c642690d612e3a3dcd54/tasks/patch_server.rb#L319) logs the status prior to the actual [reboot event test](https://github.com/albatrossflavour/puppet_os_patching/blob/389e257b41fa640a85f2c642690d612e3a3dcd54/tasks/patch_server.rb#L353).

I cannot confirm the failure to reboot because this is difficult to reproduce (it has something to do with the processes running in addition to the unavailable repo), working on that now.

**Comment by rnelson0** [comment]
Here's the replication of the problem which occurs [here](https://github.com/albatrossflavour/puppet_os_patching/blob/389e257b41fa640a85f2c642690d612e3a3dcd54/tasks/patch_server.rb#L128):
```
[root@server ~]# cat test
#!/opt/puppetlabs/puppet/bin/ruby
require 'open3'

response = ''
output, _stderr, _status = Open3.capture3('/usr/bin/needs-restarting')
puts "output = '#{output}'"
puts "stderr = '#{_stderr}'"
puts "status = '#{_status}'"
response = true unless output.empty?
puts "response = '#{response}'"

[root@server ~]# ./test
output = ''
stderr = 'Traceback (most recent call last):
  File "/usr/bin/needs-restarting", line 173, in <module>
    sys.exit(main(sys.argv))
  File "/usr/bin/needs-restarting", line 154, in main
    for oldpkg in my.pkgSack.searchFiles(just_fn): # ghostfiles are always bogons
  File "/usr/lib/python2.6/site-packages/yum/packageSack.py", line 472, in searchFiles
    return self._computeAggregateListResult("searchFiles", name)
  File "/usr/lib/python2.6/site-packages/yum/packageSack.py", line 599, in _computeAggregateListResult
    sackResult = apply(method, args)
  File "/usr/lib/python2.6/site-packages/yum/sqlitesack.py", line 46, in newFunc
    return func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/yum/sqlitesack.py", line 957, in searchFiles
    self.populate(repo, mdtype='filelists')
  File "/usr/lib/python2.6/site-packages/yum/yumRepo.py", line 173, in populate
    db_fn = repo._retrieveMD(mydbtype)
  File "/usr/lib/python2.6/site-packages/yum/yumRepo.py", line 1654, in _retrieveMD
    size=thisdata.size)
  File "/usr/lib/python2.6/site-packages/yum/yumRepo.py", line 842, in _getFile
    raise Errors.NoMoreMirrorsRepoError, errstr
yum.Errors.NoMoreMirrorsRepoError: failure: repodata/0708e3d04e17e2d229a069a9646e80019a1433a5-filelists.sqlite.bz2 from pe_repo: [Errno 256] No more mirrors to try.
'
status = 'pid 17320 exit 1'
response = ''
```
After removing the repo, the output changes:
```
[root@server ~]# rm /etc/yum.repos.d/pe_repo.repo
rm: remove regular file `/etc/yum.repos.d/pe_repo.repo'? y
[root@server ~]# ./test
output = '3949 : /sbin/mingetty/dev/tty6
3941 : /sbin/mingetty/dev/tty2
628 : /sbin/udevd-d
3945 : /sbin/mingetty/dev/tty4
3947 : /sbin/mingetty/dev/tty5
1483 : auditd
2093 : hald-addon-input: Listening on /dev/input/event2 /dev/input/event0
1775 : rpcbind
...
3969 : /sbin/udevd-d
'
stderr = ''
status = 'pid 17556 exit 0'
response = 'true'
```

**Comment by albatrossflavour** [comment]
This is odd.  The needs-restart check (with the "-r") should indicate a reboot is required by exiting with a return code of 1.  I'm checking if they've reversed this logic (exiting 0 if there's an error) if it runs into problems.  

The current code just checks for a non-zero return code so should cope OK with that scenario in the task, though the fact may need to be updated.  I'm looking into it now, but if you're able to do a 'needs-restarting -r' on an affected node and let me know the exit code, I'd appreciate it.

**Comment by albatrossflavour** [comment]
Is this, by chance, a RHEL6 based server?  If so, the problem is in the [os_patching_fact_generation.sh script](https://github.com/albatrossflavour/puppet_os_patching/blob/cb08e004400ce5ab3a770769e7df6b571d15528f/files/os_patching_fact_generation.sh#L70).

On RHEL6 is just checks for stdout to see if anything needs to be restarted.  That's the only thing I can see at the moment that would explain what you're seeing.

The fix is pretty straight forward and would be another use for the error array we discussed on the other thread.

**Comment by albatrossflavour** [comment]
Yep, must be RHEL6.  The task reboot check on 6 just checks for stdout too.

I'll start working on a fix and hopefully it'll be ready by the time you confirm.

**Comment by albatrossflavour** [comment]
I'm doing some testing on [this bug fix branch](https://github.com/albatrossflavour/puppet_os_patching/tree/bugfix/needs_restarting_improvements) - feel free to try too.

**Comment by albatrossflavour** [comment]
I'd also be interested to see what 'yum check-update' looks like on a node with the duff repos in.  Does it exit with a non-zero code etc?

**Comment by rnelson0** [comment]
@albatrossflavour In #38 it looks like the response was true unless the output was empty, now it is true if the output is empty (along with stderr). Is that correct?

**Comment by albatrossflavour** [comment]
Fixed in [PR 43](https://github.com/albatrossflavour/puppet_os_patching/pull/43)
